[package]
name = "abc186"
version = "0.1.0"
authors = ["sac4van <sac4van@local>"]
edition = "2018"

# dependencies added to new project
[dependencies]
proconio = { version = "0.3.6", features = ["derive"] }

[profile.release]
lto = true
panic = 'abort'
