[package]
name = "ant_book"
version = "0.1.0"
authors = ["sac4van <sac4van@local>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "0.4.1", features = ["derive"] }
recur-fn = "2.2.0"